config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'login' => 'sessions#new', :as => 'login'
  end
  namespace :admin do
  get 'logout' => 'sessions#destroy', :as => 'logout'
  end
  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/show'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/show'
  end

  namespace :admin do
  get 'posts/index'
  end

  get 'contact' => 'contacts#new'

  get 'contacts/create'

  get  'about' => 'about#index'

  get 'categories/show'

  get 'comments/create'

  get 'posts/index'

  get 'posts/show'
  resources :posts, :categories
  resources :contacts, only: [:new, :create]
  namespace :admin do 
    resources :posts, :categories, :comments, :users
    resources :sessions
  end
  resources :posts do
    resources :comments
  end

   root 'posts#index'

  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
	validates :name, presence: true

	def self.search(search)
  		where("name like ?", "%#{search}%") 

	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :comments

	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image, :default_url => ':style/user.jpg'
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
			
	def self.search(search)
	  where("title like ? OR body like ?", "%#{search}%", "%#{search}%") 

	end

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password
	has_many :posts
	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :password, confirmation: true

	def self.authenticaiton(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
	def self.search(search)
  		where("name like ?", "%#{search}%") 

	end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  	@categories = Category.all
  	@posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comment_params)

  	flash[:notice] = 'Comment Added'

  	redirect_to post_path(@post)
  end
  private 
  def comment_params
  	params.require(:comment).permit(:name, :email, :body, :post_id)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
 class PostsController < ApplicationController
  
  def index
    if params[:search]
    @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @posts = Post.all.order("created_at DESC").paginate(:per_page => 10, :page => params[:page])
    end
  	@categories = Category.all
  end

  def show
  	@post = Post.find(params[:id])
  	@categories = Category.all
  	@comment = Comment.new
  	@comments = Comment.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index

end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href='<%=root_path %>' class='navbar-brand' ><h1>FinestDeveloper</h1><span>/Manager</span></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller]== 'admin/posts' ? 'active' : ' ' %>"><%= link_to 'Posts', admin_posts_path %></li>
            <li class="<%= params[:controller]== 'admin/categories' ? 'active' : ' ' %>"><%= link_to 'Categories', admin_categories_path %></li>
            <li class="<%= params[:controller]== 'admin/users' ? 'active' : ' ' %>"><%= link_to 'Users', admin_users_path %></li>
          </ul>
          <%= render 'partials/admin/search' %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>  

    <section>
      <div class="container">
        <div class="row">
	        <div class="col-md-12">
            <div class="well">
              <div id="user_nav" class="pull-right">
                <% if current_user %>
                  Logged in as <%= current_user.email %>
                  <%= link_to "logout", admin_logout_path %>
                <% else %>
                  <%= link_to 'logout', admin_login_path %>
                <% end %>
              </div>
              <div class="clearfix"></div>
              <% if flash[:notice] %>
                <div class="alert alert-success"><%= flash[:notice] %></div>
              <% end %>

              <% if flash[:alert] %>
                <div class="alert alert-danger"><%= flash[:alert] %></div>
              <% end %>
              <%= yield %>
            </div>
	        </div>
        </div>
      </div>
    </section>
    <footer id="foot">
      <p>Copyright &copy; 2016, AF7 | <a href="login.html">Admin login</a> </p>
    </footer>
    
  </body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title>Login | FINESTBLOG	</title>
    <%= stylesheet_link_tag 'admin/login', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body style=" padding-top: 40px;">
 	<div class="container">

 		<%= yield %>
 	</div>
    
  </body>
</html>

app/views/partials/_comments.html.erb
		<div class="comments">
	<h2 class="page-header"><%= @post.comments.length %>Comments</h2>
	<% @post.comments.each do |comment| %>
		<div class="comment">
			<div class="row">
				<div class="col-md-2">
					<%= image_tag("user.jpg") %>
				</div>
				<div class="col-md-10">
					<div class="well">
						<h4><%= comment.name %> <span><%= comment.created_at.to_time.strftime('%B %e at %l:%M %p')%></span></h4>
						<%= comment.body %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
	<div class="well add-comment">
		<h2 class="page-header"> Add Comment</h2>
		<%= form_for([@post, @post.comments.build]) do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :email %>
				<%= f.text_field :email, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%= f.label :body %>
				<%= f.text_area :body, class: 'form-control' %>
			</div>

			<div class="form-group">
				<%= f.submit "Submit", class: 'btn btn-primary' %>

			</div>
		<% end %>
	</div>
</div>

app/views/partials/_footer.html.erb
<footer id="foot">
  <p>Copyright &copy; 2016, AF7Developers| <%= link_to 'Admin Login', admin_login_path %> </p>
</footer>

app/views/partials/_search.html.erb
<%= form_tag(posts_path, :method => 'get', id: "search-form", class: 'search-form pull-right') do %>
	    <div class="form-group">
	      <%= text_field_tag :search, params[:search], placeholder: 'Search Posts', class: 'form-control' %>
	    </div>
	    <%= submit_tag  'Search', :name => nil, class: 'btn btn-primary' %>
<% end %>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'posts' || params[:controller] == 'categories' %>
<div class="list-group">
	<% @categories.each do |category| %>
		<%= link_to category.name, category_path(category.id), class: 'list-group-item' %>
	<% end %>
</div>
<% end %>

app/views/partials/admin/_search.html.erb
<% if params[:controller] == 'admin/posts' %>
	<%= form_tag(admin_posts_path, :method => 'get', id: "search-form", class: 'search-form pull-right') do %>
	    <div class="form-group">
	      <%= text_field_tag :search, params[:search], placeholder: 'Search Posts', class:'form-control' %>
	    </div>
	    <%= submit_tag  'Search', :name => nil, class:'btn btn-primary' %>
	<% end %>
<% elsif params[:controller] == 'admin/categories' %>
	<%= form_tag(admin_categories_path, :method => 'get', id: "search-form", class: 'search-form pull-right') do %>
	    <div class="form-group">
	      <%= text_field_tag :search, params[:search], placeholder: 'Search Categories', class:'form-control' %>
	    </div>
	    <%= submit_tag  'Search', :name => nil, class:'btn btn-primary' %>
	<% end %>
<% elsif params[:controller] == 'admin/users' %>
	<%= form_tag(admin_users_path, :method => 'get', id: "search-form", class: 'search-form pull-right') do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: 'Search Users', class:'form-control' %>
    </div>
    <%= submit_tag  'Search', :name => nil, class:'btn btn-primary' %>
	<% end %>
<% end %>